/*
 * Este codigo fue creado por @DuvanBotello
 *  <"Sin lógica no hay paraíso">
 */
package GUI;

import javax.swing.JOptionPane;
import Abstracciones.*;

/**
 *
 * @author DuvanBotello
 * <http://yoaprendo-informatica.blogspot.com.co/ - duvanbotello1008@gmail.com>
 */
public class Admin_Contraseña extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admin_Contraseña
     */
    public Admin_Contraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_admin_doc = new javax.swing.JTextField();
        lb_nombre = new javax.swing.JLabel();
        lb_nombre1 = new javax.swing.JLabel();
        txt_admin_nombre = new javax.swing.JTextField();
        lb_nombre2 = new javax.swing.JLabel();
        txt_contraseña = new javax.swing.JTextField();
        btm_registrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Asignar Contraseña");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Asignar Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        txt_admin_doc.setEditable(false);
        txt_admin_doc.setBackground(new java.awt.Color(0, 204, 102));
        txt_admin_doc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_admin_doc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_admin_doc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_admin_docKeyTyped(evt);
            }
        });

        lb_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre.setText("Doc :");

        lb_nombre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre1.setText("Nombre:");

        txt_admin_nombre.setEditable(false);
        txt_admin_nombre.setBackground(new java.awt.Color(0, 204, 102));
        txt_admin_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_admin_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_admin_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_admin_nombreKeyTyped(evt);
            }
        });

        lb_nombre2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre2.setText("Contraseña :");

        txt_contraseña.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_contraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_contraseñaKeyTyped(evt);
            }
        });

        btm_registrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btm_registrar.setForeground(new java.awt.Color(0, 153, 0));
        btm_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados_icono.png"))); // NOI18N
        btm_registrar.setText("Crear Rol");
        btm_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_nombre2)
                    .addComponent(lb_nombre)
                    .addComponent(lb_nombre1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_admin_doc)
                    .addComponent(txt_admin_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(txt_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(btm_registrar)
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombre)
                    .addComponent(txt_admin_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombre1)
                    .addComponent(txt_admin_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombre2)
                    .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btm_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_admin_docKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_admin_docKeyTyped

    }//GEN-LAST:event_txt_admin_docKeyTyped

    private void txt_admin_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_admin_nombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_admin_nombreKeyTyped

    private void txt_contraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contraseñaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraseñaKeyTyped

    private void btm_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_registrarActionPerformed
         
        if (!txt_contraseña.getText().isEmpty()) {
            if (txt_contraseña.getText().length() >= 6) {
              
               
                Metodos.metodos.InsertarAdmin(new Abs_Administradores(txt_admin_doc.getText(),txt_admin_nombre.getText(), txt_contraseña.getText()));
                
            } else {
                JOptionPane.showMessageDialog(null, "La contraseña debe tener mas de 6 digitos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Digitar Contraseña");
        }

    }//GEN-LAST:event_btm_registrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_registrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_nombre1;
    private javax.swing.JLabel lb_nombre2;
    public static javax.swing.JTextField txt_admin_doc;
    public static javax.swing.JTextField txt_admin_nombre;
    private javax.swing.JTextField txt_contraseña;
    // End of variables declaration//GEN-END:variables
}
