/*
 * Este codigo fue creado por @DuvanBotello
 *  <"Sin lógica no hay paraíso">
 */
package GUI;

import Abstracciones.*;
import Metodos.Render;
import Metodos.metodos;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DuvanBotello
 * <http://yoaprendo-informatica.blogspot.com.co/ - duvanbotello1008@gmail.com>
 */
public class AsignarProyec extends javax.swing.JInternalFrame {

    public static long codigo1;
    public static String departamento;

    DefaultTableModel modelo_tb1 = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    DefaultTableModel modelo_tb2 = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    JButton btn1 = new JButton("Asignar");
    JButton btn2 = new JButton("Eliminar");

    /**
     * Creates new form AsignarProyec
     */
    public AsignarProyec() {
        initComponents();
       
        cargarTabla1();
    }

    public static void codigo(long codigo, String departamento1) {
        codigo1 = codigo;
        departamento = departamento1;
    }

    

    private void cargarTabla1() {
        tb1.setModel(modelo_tb1);
        modelo_tb1.setRowCount(0);
        tb1.setRowHeight(30);
        tb1.setDefaultRenderer(Object.class, new Render());
        btn2.setName("btm_eliminar");

        modelo_tb1.addColumn("Numero Asignado");
        modelo_tb1.addColumn("Nombre");
        modelo_tb1.addColumn("Descripcion");
        modelo_tb1.addColumn("fecha_i");
        modelo_tb1.addColumn("fecha_f");
        modelo_tb1.addColumn("Eliminar");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_titulo = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_departamento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        btm_cargar = new javax.swing.JButton();
        lb_nombre6 = new javax.swing.JLabel();
        combo_busqueda1 = new javax.swing.JComboBox<>();
        txt_buscar1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Asignar Proyecto");

        panel_titulo.setBackground(new java.awt.Color(0, 153, 255));
        panel_titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_titulo.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo.setText("Ver proyectos de Departamento");

        javax.swing.GroupLayout panel_tituloLayout = new javax.swing.GroupLayout(panel_titulo);
        panel_titulo.setLayout(panel_tituloLayout);
        panel_tituloLayout.setHorizontalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_titulo)
                .addGap(95, 95, 95))
        );
        panel_tituloLayout.setVerticalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tituloLayout.createSequentialGroup()
                .addComponent(lb_titulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Proyectos de Departamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lb_departamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_departamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        btm_cargar.setText("Cargar Proyectos");
        btm_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_cargarActionPerformed(evt);
            }
        });

        lb_nombre6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre6.setText("Buscar por:");

        combo_busqueda1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_busqueda1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "NUMERO ASOCIADO", "NOMBRE" }));

        txt_buscar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_buscar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_buscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscar1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_departamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lb_nombre6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_busqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btm_cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lb_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_nombre6)
                        .addComponent(combo_busqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btm_cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private TableRowSorter<TableModel> trs;
    private void btm_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_cargarActionPerformed
        modelo_tb1.setRowCount(0);
        for (Abs_departamentos d : metodos.lista_departamentos) {
            if (codigo1 == d.getCodigo()) {
                Object file[] = new Object[tb1.getColumnCount()];
                for (Abs_proyectos p : d.getListaproyecto()) {
                    file[0] = p.getNumero_empleados();
                    file[1] = p.getNombre();
                    file[2] = p.getDescripcion();
                    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                    file[3] = formato.format(p.getFecha_f());
                    file[4] = formato.format(p.getFecha_i());
                    file[5] = btn2;
                    modelo_tb1.addRow(file);
                }
            }
        }
    }//GEN-LAST:event_btm_cargarActionPerformed

    private void txt_buscar1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscar1KeyTyped
        switch (combo_busqueda1.getSelectedIndex()) {
            case 1:

                txt_buscar1.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt_buscar1.getText(), 0));
                    }

                });
                trs = new TableRowSorter<>(tb1.getModel());
                tb1.setRowSorter(trs);
                break;
            case 2:
                txt_buscar1.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt_buscar1.getText(), 1));
                    }

                });
                trs = new TableRowSorter<>(tb1.getModel());
                tb1.setRowSorter(trs);

                break;
            default:
                JOptionPane.showMessageDialog(null, "Por favor seleccione un tipo de busqueda");

                break;
        }
    }//GEN-LAST:event_txt_buscar1KeyTyped

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        int seleccion = tb1.rowAtPoint(evt.getPoint());

        String numero = String.valueOf(tb1.getValueAt(seleccion, 0));
        long numero1 = Long.parseLong(numero);

        //CON ESTO AGARRO LA POSICION X Y LA Y PARA SABER LA UBICACION
        int column = tb1.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tb1.getRowHeight();

        if (row < tb1.getRowCount() && row >= 0 && column < tb1.getColumnCount() && column >= 0) {
            Object value = tb1.getValueAt(row, column);
            //SI LA POCICION DONDE SE DIO CLIK ES UN BOTON SE PUEDE EJECUTAR EL CODIGO
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("btm_eliminar")) {

                    for (Abs_departamentos d : metodos.lista_departamentos) {
                        if (AsignarProyec.codigo1 == d.getCodigo()) {
                            for (Abs_proyectos p : d.getListaproyecto()) {
                                if (numero1 == p.getNumero_empleados()) {
                                    d.getListaproyecto().remove(p);
                                    break;
                                }
                            }

                        }
                    }
                    metodos.actulizar_listaanidada_departamentos(departamento, codigo1);
                    btm_cargar.doClick();
                    JOptionPane.showMessageDialog(null, "Eliminado Con Exito");

                }

            }

        }
    }//GEN-LAST:event_tb1MouseClicked
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_cargar;
    private javax.swing.JComboBox<String> combo_busqueda1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lb_departamento;
    private javax.swing.JLabel lb_nombre6;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JPanel panel_titulo;
    public static javax.swing.JTable tb1;
    private javax.swing.JTextField txt_buscar1;
    // End of variables declaration//GEN-END:variables
}
