/*
 * Este codigo fue creado por @DuvanBotello
 *  <"Sin lógica no hay paraíso">
 */
package GUI;

import Abstracciones.Abs_departamentos;
import Abstracciones.Abs_empleados;
import Abstracciones.Abs_proyectos;
import Metodos.Render;
import Metodos.metodos;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DuvanBotello
 * <http://yoaprendo-informatica.blogspot.com.co/ - duvanbotello1008@gmail.com>
 */
public class Mantenimiento extends javax.swing.JInternalFrame {

    DefaultTableModel modelo_empleado = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    DefaultTableModel modelo_proyectos = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    DefaultTableModel modelo_departamentos = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    JButton btn1 = new JButton("Modificar");
    JButton btn2 = new JButton("Ver Encargado");
    JButton btn3 = new JButton("Ver Listado");
    private TableRowSorter<TableModel> trs;

    /**
     * Creates new form Mantenimiento
     */
    public Mantenimiento() {
        initComponents();
        cargar();
        cargarProyectos();
        cargar_modelo_emple();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_titulo = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txt = new javax.swing.JTextField();
        combo_busqueda = new javax.swing.JComboBox<>();
        lb_nombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        btm_actualizar22 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txt1 = new javax.swing.JTextField();
        combo_busqueda1 = new javax.swing.JComboBox<>();
        lb_nombre1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_proyectos = new javax.swing.JTable();
        btm_actualizar23 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_departamentos = new javax.swing.JTable();
        combo_busqueda2 = new javax.swing.JComboBox<>();
        lb_nombre2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        btm_actualizar_departamentos = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Mantenimiento");

        panel_titulo.setBackground(new java.awt.Color(51, 51, 51));
        panel_titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_titulo.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo.setText("Mantenimiento");

        javax.swing.GroupLayout panel_tituloLayout = new javax.swing.GroupLayout(panel_titulo);
        panel_titulo.setLayout(panel_tituloLayout);
        panel_tituloLayout.setHorizontalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(lb_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_tituloLayout.setVerticalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloLayout.createSequentialGroup()
                .addComponent(lb_titulo)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Mantenimiento De Empleados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(153, 153, 153));

        txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKeyTyped(evt);
            }
        });

        combo_busqueda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_busqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "DOCUMENTO", "NOMBRE" }));

        lb_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre.setText("Buscar por:");

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        btm_actualizar22.setText("Actualizar");
        btm_actualizar22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_actualizar22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lb_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btm_actualizar22, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nombre)
                    .addComponent(combo_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_actualizar22))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empleados", jPanel1);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Mantenimiento Proyectos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txt1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });

        combo_busqueda1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_busqueda1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "CODIGO PROYECTO", "NOMBRE PROYECTO" }));

        lb_nombre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre1.setText("Buscar por:");

        tb_proyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_proyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_proyectosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_proyectos);

        btm_actualizar23.setText("Actualizar");
        btm_actualizar23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_actualizar23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lb_nombre1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_busqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btm_actualizar23, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nombre1)
                    .addComponent(combo_busqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_actualizar23))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Proyectos", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Buscar Departamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tb_departamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_departamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_departamentosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_departamentos);

        combo_busqueda2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_busqueda2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "NOMBRE", "CODIGO" }));

        lb_nombre2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre2.setText("Buscar por:");

        txt2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt2KeyTyped(evt);
            }
        });

        btm_actualizar_departamentos.setText("Actualizar");
        btm_actualizar_departamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_actualizar_departamentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(lb_nombre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_busqueda2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btm_actualizar_departamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nombre2)
                    .addComponent(combo_busqueda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_actualizar_departamentos))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Departamentos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   private void cargar() {
        tb_departamentos.setModel(modelo_departamentos);
        tb_departamentos.setRowHeight(30);
        tb_departamentos.setDefaultRenderer(Object.class, new Render());

        btn2.setName("btm_ver");
        btn3.setName("btm_asignar");

        modelo_departamentos.addColumn("Nombre Departamento");
        modelo_departamentos.addColumn("Codigo");
        modelo_departamentos.addColumn("Encargado");
        modelo_departamentos.addColumn("Fecha de Inicio");
        modelo_departamentos.addColumn("Ver/Asignar Proyectos");
        modelo_departamentos.addColumn("Modificar");

        tb_departamentos.setModel(modelo_departamentos);
        cargar_tabla_despartamentos();

    }

    private void cargar_tabla_despartamentos() {
        modelo_departamentos.setRowCount(0);
        Object[] file = new Object[tb_departamentos.getColumnCount()];
        for (Abs_departamentos d : metodos.lista_departamentos) {

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            file[0] = d.getNombre();
            file[1] = d.getCodigo();
            file[2] = d.getEmple().getDocumento();
            file[3] = formato.format(d.getFecha_dirige());
            file[4] = btn3;
            file[5] = btn1;
            modelo_departamentos.addRow(file);
        }
    }

    private void cargarProyectos() {
        tb_proyectos.setModel(modelo_proyectos);
        modelo_proyectos.setRowCount(0);
        tb_proyectos.setRowHeight(30);
        tb_proyectos.setDefaultRenderer(Object.class, new Render());
        btn1.setName("btm_modificar");

        modelo_proyectos.addColumn("Numero Asignado");
        modelo_proyectos.addColumn("Nombre");
        modelo_proyectos.addColumn("Descripcion");
        modelo_proyectos.addColumn("fecha_i");
        modelo_proyectos.addColumn("fecha_f");
        modelo_proyectos.addColumn("Empleado");
        modelo_proyectos.addColumn("Eliminar");
        cargarTablaProyectos();

    }

    private void cargarTablaProyectos() {
        modelo_proyectos.setRowCount(0);
        Object[] file = new Object[tb_proyectos.getColumnCount()];
        for (Abs_proyectos p : metodos.lista_proyectos) {
            file[0] = p.getNumero_empleados();
            file[1] = p.getNombre();
            file[2] = p.getDescripcion();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            file[3] = formato.format(p.getFecha_i());
            file[4] = formato.format(p.getFecha_f());
            file[5] = p.getDoc_empleado();
            file[6] = btn1;
            modelo_proyectos.addRow(file);
        }
    }

    private void cargar_modelo_emple() {
        tb1.setModel(modelo_empleado);
        tb1.setRowHeight(30);
        tb1.setDefaultRenderer(Object.class, new Render());

        btn1.setName("btm_modificar");

        modelo_empleado.addColumn("Documento");
        modelo_empleado.addColumn("Nombre");
        modelo_empleado.addColumn("Num_Seguridad");
        modelo_empleado.addColumn("Direccion");
        modelo_empleado.addColumn("Sueldo");
        modelo_empleado.addColumn("Genero");
        modelo_empleado.addColumn("Hijos");
        modelo_empleado.addColumn("Fecha_na");
        modelo_empleado.addColumn("DeparAsig");
        modelo_empleado.addColumn("Modificar");
        tb1.setModel(modelo_empleado);
        cargar_tabla_empleados();

    }

    private void cargar_tabla_empleados() {
        modelo_empleado.setRowCount(0);
        Object[] file = new Object[tb1.getColumnCount()];
        for (Abs_empleados e : metodos.lista_empleados) {
            file[0] = e.getDocumento();
            file[1] = e.getNombre_emple();
            file[2] = e.getNum_seguridad_s();
            file[3] = e.getDireccion();
            file[4] = e.getSueldo();
            file[5] = e.getGenero();
            file[6] = e.getNumero_hijos();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            file[7] = formato.format(e.getFecha_nacimiento());
            file[8] = e.getDepartamento_asignado();
            file[9] = btn1;
            modelo_empleado.addRow(file);
        }
    }

    private void txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyTyped
        switch (combo_busqueda.getSelectedIndex()) {
            case 1:

                txt.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt.getText(), 0));
                    }

                });
                trs = new TableRowSorter<>(tb1.getModel());
                tb1.setRowSorter(trs);
                break;
            case 2:
                txt.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt.getText(), 1));
                    }

                });
                trs = new TableRowSorter<>(tb1.getModel());
                tb1.setRowSorter(trs);

                break;
            default:
                JOptionPane.showMessageDialog(null, "Por favor seleccione un tipo de busqueda");

                break;
        }


    }//GEN-LAST:event_txtKeyTyped

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        int seleccion = tb1.rowAtPoint(evt.getPoint());

        String documento = String.valueOf(tb1.getValueAt(seleccion, 0));
        String nombre = String.valueOf(tb1.getValueAt(seleccion, 1));
        String num_Se = String.valueOf(tb1.getValueAt(seleccion, 2));
        String direccion = String.valueOf(tb1.getValueAt(seleccion, 3));
        String sueldo = String.valueOf(tb1.getValueAt(seleccion, 4));
        String genero = String.valueOf(tb1.getValueAt(seleccion, 5));
        String hijos = String.valueOf(tb1.getValueAt(seleccion, 6));
        String fecha_n = String.valueOf(tb1.getValueAt(seleccion, 7));

        //CON ESTO AGARRO LA POSICION X Y LA Y PARA SABER LA UBICACION
        int column = tb1.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tb1.getRowHeight();

        if (row < tb1.getRowCount() && row >= 0 && column < tb1.getColumnCount() && column >= 0) {
            Object value = tb1.getValueAt(row, column);
            //SI LA POCICION DONDE SE DIO CLIK ES UN BOTON SE PUEDE EJECUTAR EL CODIGO
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("btm_modificar")) {
                    Mempleados d = new Mempleados();
                    Principal.escritorio.add(d);
                    d.show();
                    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                    Mempleados.txt_doc.setText(documento);
                    Mempleados.txt_nombre.setText(nombre);
                    Mempleados.txt_numero_social.setText(num_Se);
                    Mempleados.txt_direccion.setText(direccion);
                    Mempleados.txt_salario.setText(sueldo);
                    Mempleados.txt_genero.setSelectedIndex(Integer.parseInt(genero));
                    Mempleados.txt_hijos.setText(hijos);
                    try {
                        Mempleados.txt_fecha.setDate(formato.parse(fecha_n));
                    } catch (ParseException ex) {
                        Logger.getLogger(Mantenimiento.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }

        }
    }//GEN-LAST:event_tb1MouseClicked

    private void btm_actualizar22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_actualizar22ActionPerformed
        cargar_tabla_empleados();
    }//GEN-LAST:event_btm_actualizar22ActionPerformed

    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
        switch (combo_busqueda1.getSelectedIndex()) {
            case 1:

                txt1.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt1.getText(), 0));
                    }

                });
                trs = new TableRowSorter<>(tb_proyectos.getModel());
                tb_proyectos.setRowSorter(trs);
                break;
            case 2:
                txt1.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt1.getText(), 1));
                    }

                });
                trs = new TableRowSorter<>(tb_proyectos.getModel());
                tb_proyectos.setRowSorter(trs);

                break;
            default:
                JOptionPane.showMessageDialog(null, "Por favor seleccione un tipo de busqueda");

                break;
        }
    }//GEN-LAST:event_txt1KeyTyped

    private void tb_proyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_proyectosMouseClicked
        int seleccion = tb_proyectos.rowAtPoint(evt.getPoint());

        String numero_asociado = String.valueOf(tb_proyectos.getValueAt(seleccion, 0));
        String nombre = String.valueOf(tb_proyectos.getValueAt(seleccion, 1));
        String descripcion = String.valueOf(tb_proyectos.getValueAt(seleccion, 2));
        String fecha_i = String.valueOf(tb_proyectos.getValueAt(seleccion, 3));
        String fecha_f = String.valueOf(tb_proyectos.getValueAt(seleccion, 4));
        String doc_empleado = String.valueOf(tb_proyectos.getValueAt(seleccion, 5));

        //CON ESTO AGARRO LA POSICION X Y LA Y PARA SABER LA UBICACION
        int column = tb_proyectos.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tb_proyectos.getRowHeight();

        if (row < tb_proyectos.getRowCount() && row >= 0 && column < tb_proyectos.getColumnCount() && column >= 0) {
            Object value = tb_proyectos.getValueAt(row, column);
            //SI LA POCICION DONDE SE DIO CLIK ES UN BOTON SE PUEDE EJECUTAR EL CODIGO
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("btm_modificar")) {
                    Mproyectos m = new Mproyectos();
                    Principal.escritorio.add(m);
                    m.show();
                    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                    Mproyectos.txt_codigo_asociado.setText(numero_asociado);
                    Mproyectos.txt_descripcion.setText(descripcion);
                    Mproyectos.txt_nombre_proyecto.setText(nombre);
                    Mproyectos.txt_doc_empe.setText(doc_empleado);
                    try {
                        Mproyectos.fecha_inicio.setDate(formato.parse(fecha_i));
                        Mproyectos.fecha_final.setDate(formato.parse(fecha_f));
                    } catch (ParseException ex) {
                        Logger.getLogger(Mantenimiento.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }

        }
    }//GEN-LAST:event_tb_proyectosMouseClicked

    private void btm_actualizar23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_actualizar23ActionPerformed
        cargarTablaProyectos();
    }//GEN-LAST:event_btm_actualizar23ActionPerformed

    private void tb_departamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_departamentosMouseClicked
        int seleccion = tb_departamentos.rowAtPoint(evt.getPoint());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String codigo1 = String.valueOf(tb_departamentos.getValueAt(seleccion, 1));
        String nombre = String.valueOf(tb_departamentos.getValueAt(seleccion, 0));
        String doc_emp = String.valueOf(tb_departamentos.getValueAt(seleccion, 2));
        String fecha2 = String.valueOf(tb_departamentos.getValueAt(seleccion, 3));
        long codigo = Long.parseLong(codigo1);
        long doc_emple = Long.parseLong(doc_emp);

        //CON ESTO AGARRO LA POSICION X Y LA Y PARA SABER LA UBICACION
        int column = tb_departamentos.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tb_departamentos.getRowHeight();

        if (row < tb_departamentos.getRowCount() && row >= 0 && column < tb_departamentos.getColumnCount() && column >= 0) {
            Object value = tb_departamentos.getValueAt(row, column);
            //SI LA POCICION DONDE SE DIO CLIK ES UN BOTON SE PUEDE EJECUTAR EL CODIGO
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("btm_modificar")) {
                    MDepartamentos d = new MDepartamentos();
                    Principal.escritorio.add(d);
                    d.show();
                    try {
                        Date fecha_inici = formato.parse(fecha2);
                        MDepartamentos.mfecha_departamento.setDate(fecha_inici);
                    } catch (ParseException ex) {
                        Logger.getLogger(Mantenimiento.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    MDepartamentos.mtxt_doc_empe.setText(doc_emp);
                    MDepartamentos.mtxt_codigo_departamento.setText(codigo1);
                    MDepartamentos.mtxt_nombre_departamento.setText(nombre);

                }

                if (boton.getName().equals("btm_asignar")) {
                    AsignarProyec d = new AsignarProyec();
                    Principal.escritorio.add(d);
                    d.show();
                    AsignarProyec.lb_departamento.setText("Lista de proyectos del departamento de " + nombre + ".");
                    AsignarProyec.codigo(codigo, nombre);
                }
            }

        }
    }//GEN-LAST:event_tb_departamentosMouseClicked

    private void txt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyTyped
        switch (combo_busqueda2.getSelectedIndex()) {
            case 1:

                txt2.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt2.getText(), 0));
                    }

                });
                trs = new TableRowSorter<>(tb_departamentos.getModel());
                tb_departamentos.setRowSorter(trs);
                break;
            case 2:
                txt2.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt2.getText(), 1));
                    }

                });
                trs = new TableRowSorter<>(tb_departamentos.getModel());
                tb_departamentos.setRowSorter(trs);

                break;
            default:
                JOptionPane.showMessageDialog(null, "Por favor seleccione un tipo de busqueda");

                break;
        }
    }//GEN-LAST:event_txt2KeyTyped

    private void btm_actualizar_departamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_actualizar_departamentosActionPerformed
        modelo_departamentos.setRowCount(0);
        Object[] file = new Object[tb_departamentos.getColumnCount()];
        for (Abs_departamentos d : metodos.lista_departamentos) {

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            file[0] = d.getNombre();
            file[1] = d.getCodigo();
            file[2] = d.getEmple().getDocumento();
            file[3] = formato.format(d.getFecha_dirige());
            file[4] = btn3;
            file[5] = btn1;
            modelo_departamentos.addRow(file);
        }
    }//GEN-LAST:event_btm_actualizar_departamentosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btm_actualizar22;
    public static javax.swing.JButton btm_actualizar23;
    public static javax.swing.JButton btm_actualizar_departamentos;
    private javax.swing.JComboBox<String> combo_busqueda;
    private javax.swing.JComboBox<String> combo_busqueda1;
    private javax.swing.JComboBox<String> combo_busqueda2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_nombre1;
    private javax.swing.JLabel lb_nombre2;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JPanel panel_titulo;
    public static javax.swing.JTable tb1;
    private javax.swing.JTable tb_departamentos;
    public static javax.swing.JTable tb_proyectos;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
