/*
 * Este codigo fue creado por @DuvanBotello
 *  <"Sin lógica no hay paraíso">
 */
package GUI;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author DuvanBotello
 * <http://yoaprendo-informatica.blogspot.com.co/ - duvanbotello1008@gmail.com>
 */
public class MDepartamentos extends javax.swing.JInternalFrame {

    /**
     * Creates new form MDepartamentos
     */
    public MDepartamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_titulo = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_nombre = new javax.swing.JLabel();
        mtxt_nombre_departamento = new javax.swing.JTextField();
        lb_nombre1 = new javax.swing.JLabel();
        mtxt_codigo_departamento = new javax.swing.JTextField();
        mfecha_departamento = new com.toedter.calendar.JDateChooser();
        lb_nombre3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lb_nombre5 = new javax.swing.JLabel();
        mtxt_nombre_empleado = new javax.swing.JTextField();
        btm_buscar_empleado = new javax.swing.JButton();
        mtxt_documento_empleado = new javax.swing.JTextField();
        lb_nombre6 = new javax.swing.JLabel();
        mtxt_doc_empe = new javax.swing.JTextField();
        lb_nombre7 = new javax.swing.JLabel();
        btm_registrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Modificar Departamentos");

        panel_titulo.setBackground(new java.awt.Color(255, 102, 102));
        panel_titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_titulo.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo.setText("Modificar Departamentos");

        javax.swing.GroupLayout panel_tituloLayout = new javax.swing.GroupLayout(panel_titulo);
        panel_titulo.setLayout(panel_tituloLayout);
        panel_tituloLayout.setHorizontalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_titulo)
                .addGap(40, 40, 40))
        );
        panel_tituloLayout.setVerticalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloLayout.createSequentialGroup()
                .addComponent(lb_titulo)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Modificacion de Departamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lb_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre.setText("Nombre de Departamento:");

        mtxt_nombre_departamento.setEditable(false);
        mtxt_nombre_departamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mtxt_nombre_departamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mtxt_nombre_departamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mtxt_nombre_departamentoKeyTyped(evt);
            }
        });

        lb_nombre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre1.setText("Codigo de departamento:");

        mtxt_codigo_departamento.setEditable(false);
        mtxt_codigo_departamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mtxt_codigo_departamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mtxt_codigo_departamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mtxt_codigo_departamentoKeyTyped(evt);
            }
        });

        lb_nombre3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre3.setText("Fecha de Iniciacion : ");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Buscar Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lb_nombre5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre5.setText("Nombre Empleado:");

        mtxt_nombre_empleado.setEditable(false);
        mtxt_nombre_empleado.setBackground(new java.awt.Color(51, 153, 255));
        mtxt_nombre_empleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mtxt_nombre_empleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mtxt_nombre_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mtxt_nombre_empleadoKeyTyped(evt);
            }
        });

        btm_buscar_empleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btm_buscar_empleado.setForeground(new java.awt.Color(51, 153, 255));
        btm_buscar_empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados_icono.png"))); // NOI18N
        btm_buscar_empleado.setText("Buscar");
        btm_buscar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_buscar_empleadoActionPerformed(evt);
            }
        });

        mtxt_documento_empleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mtxt_documento_empleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mtxt_documento_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mtxt_documento_empleadoKeyTyped(evt);
            }
        });

        lb_nombre6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre6.setText("Digete Documento:");

        mtxt_doc_empe.setEditable(false);
        mtxt_doc_empe.setBackground(new java.awt.Color(51, 153, 255));
        mtxt_doc_empe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mtxt_doc_empe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mtxt_doc_empe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mtxt_doc_empeKeyTyped(evt);
            }
        });

        lb_nombre7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre7.setText("Documento :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_nombre6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mtxt_documento_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btm_buscar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mtxt_nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lb_nombre5)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(mtxt_doc_empe, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lb_nombre7)))
                        .addGap(36, 36, 36))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mtxt_documento_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nombre6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btm_buscar_empleado)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_nombre5)
                            .addComponent(lb_nombre7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mtxt_nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mtxt_doc_empe, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btm_registrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btm_registrar.setForeground(new java.awt.Color(255, 51, 51));
        btm_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/departamentos_icono.png"))); // NOI18N
        btm_registrar.setText("Modificar Departamento");
        btm_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_nombre1)
                            .addComponent(lb_nombre)
                            .addComponent(lb_nombre3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mtxt_nombre_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mtxt_codigo_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(mfecha_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btm_registrar)
                .addGap(141, 141, 141))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombre)
                    .addComponent(mtxt_nombre_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombre1)
                    .addComponent(mtxt_codigo_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nombre3)
                    .addComponent(mfecha_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btm_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mtxt_nombre_departamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mtxt_nombre_departamentoKeyTyped
        char teclaseleccionada = evt.getKeyChar();
        if (teclaseleccionada == KeyEvent.VK_ENTER || teclaseleccionada == KeyEvent.VK_I) {
            btm_registrar.doClick();
        }
    }//GEN-LAST:event_mtxt_nombre_departamentoKeyTyped

    private void mtxt_codigo_departamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mtxt_codigo_departamentoKeyTyped
        char teclaseleccionada = evt.getKeyChar();
        if (teclaseleccionada == KeyEvent.VK_ENTER || teclaseleccionada == KeyEvent.VK_I) {
            btm_registrar.doClick();
        }

        if (Character.isLetter(teclaseleccionada)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO SE PUEDEN INGRESAR NUMEROS EN EL CAMPO");
        }
    }//GEN-LAST:event_mtxt_codigo_departamentoKeyTyped

    private void mtxt_nombre_empleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mtxt_nombre_empleadoKeyTyped

    }//GEN-LAST:event_mtxt_nombre_empleadoKeyTyped

    private void btm_buscar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_buscar_empleadoActionPerformed

        if (!mtxt_documento_empleado.getText().isEmpty()) {
            boolean existe = false;
            long doc_emple = Long.parseLong(mtxt_documento_empleado.getText().trim());
            for (Abstracciones.Abs_empleados e : Metodos.metodos.lista_empleados) {
                if (e.getDocumento() == doc_emple) {
                    mtxt_nombre_empleado.setText(e.getNombre_emple());
                    mtxt_doc_empe.setText(Long.toString(e.getDocumento()));
                    existe = true;
                    JOptionPane.showMessageDialog(null, "EMPLEADO ENCONTRADO CON EXITO");
                    mtxt_documento_empleado.setText("");
                    break;
                }
            }
            if (existe == false) {
                JOptionPane.showMessageDialog(null, "EMPLEADO NO EXISTE");
            }
        } else {
            JOptionPane.showMessageDialog(null, "INGRESE DOCUMENTO");
        }
    }//GEN-LAST:event_btm_buscar_empleadoActionPerformed

    private void mtxt_documento_empleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mtxt_documento_empleadoKeyTyped
        char teclaseleccionada = evt.getKeyChar();
        if (teclaseleccionada == KeyEvent.VK_ENTER || teclaseleccionada == KeyEvent.VK_I) {
            btm_buscar_empleado.doClick();
        }
    }//GEN-LAST:event_mtxt_documento_empleadoKeyTyped

    private void mtxt_doc_empeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mtxt_doc_empeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_mtxt_doc_empeKeyTyped

    private void btm_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_registrarActionPerformed
        if (!mtxt_nombre_departamento.getText().isEmpty()) {
            if (!mtxt_doc_empe.getText().isEmpty()) {
                if (mfecha_departamento.getDate() != null) {

                    for (Abstracciones.Abs_departamentos d : Metodos.metodos.lista_departamentos) {
                        if (Long.parseLong(mtxt_codigo_departamento.getText()) == d.getCodigo()) {
                            d.setFecha_dirige(mfecha_departamento.getDate());
                            Abstracciones.Abs_empleados empleado = null;
                            System.out.println("dddddddd");
                            for (Abstracciones.Abs_empleados e : Metodos.metodos.lista_empleados) {
                                if (e.getDocumento() == Long.parseLong(mtxt_doc_empe.getText())) {
                                    empleado = e;
                                    break;
                                }
                            }
                            d.setEmple(empleado);
                            Metodos.metodos.guarda_modificacion_departaemntos();
                            Mantenimiento.btm_actualizar_departamentos.doClick();
                            JOptionPane.showMessageDialog(null, "DEPARTAMENTO MODIFICADO");
                            break;

                        }

                    }

                } else {
                    JOptionPane.showMessageDialog(null, "INGRESE DOCUMENTO FECHA");
                }

            } else {
                JOptionPane.showMessageDialog(null, "INGRESE DOCUMENTO DE EMPLEADO");
            }
        } else {
            JOptionPane.showMessageDialog(null, "INGRESE NOMBRE");
        }
    }//GEN-LAST:event_btm_registrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_buscar_empleado;
    private javax.swing.JButton btm_registrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_nombre1;
    private javax.swing.JLabel lb_nombre3;
    private javax.swing.JLabel lb_nombre5;
    private javax.swing.JLabel lb_nombre6;
    private javax.swing.JLabel lb_nombre7;
    private javax.swing.JLabel lb_titulo;
    public static com.toedter.calendar.JDateChooser mfecha_departamento;
    public static javax.swing.JTextField mtxt_codigo_departamento;
    public static javax.swing.JTextField mtxt_doc_empe;
    private javax.swing.JTextField mtxt_documento_empleado;
    public static javax.swing.JTextField mtxt_nombre_departamento;
    public static javax.swing.JTextField mtxt_nombre_empleado;
    private javax.swing.JPanel panel_titulo;
    // End of variables declaration//GEN-END:variables
}
