/*
 * Este codigo fue creado por @DuvanBotello
 *  <"Sin lógica no hay paraíso">
 */
package GUI;

import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author DuvanBotello
 * <http://yoaprendo-informatica.blogspot.com.co/ - duvanbotello1008@gmail.com>
 */
public class Mproyectos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Mproyectos
     */
    public Mproyectos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_titulo = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_codigo_asociado = new javax.swing.JTextField();
        lb_nombre1 = new javax.swing.JLabel();
        txt_nombre_proyecto = new javax.swing.JTextField();
        lb_nombre = new javax.swing.JLabel();
        lb_nombre2 = new javax.swing.JLabel();
        lb_nombre3 = new javax.swing.JLabel();
        fecha_inicio = new com.toedter.calendar.JDateChooser();
        lb_nombre4 = new javax.swing.JLabel();
        fecha_final = new com.toedter.calendar.JDateChooser();
        txt_descripcion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lb_nombre5 = new javax.swing.JLabel();
        txt_nombre_empleado = new javax.swing.JTextField();
        btm_buscar_empleado = new javax.swing.JButton();
        txt_documento_empleado = new javax.swing.JTextField();
        lb_nombre6 = new javax.swing.JLabel();
        txt_doc_empe = new javax.swing.JTextField();
        lb_nombre7 = new javax.swing.JLabel();
        btm_registrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Mantenimiento De Proyectos");

        panel_titulo.setBackground(new java.awt.Color(255, 102, 102));
        panel_titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_titulo.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo.setText("Modificar Proyectos");

        javax.swing.GroupLayout panel_tituloLayout = new javax.swing.GroupLayout(panel_titulo);
        panel_titulo.setLayout(panel_tituloLayout);
        panel_tituloLayout.setHorizontalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(lb_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_tituloLayout.setVerticalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloLayout.createSequentialGroup()
                .addComponent(lb_titulo)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos de proyecto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txt_codigo_asociado.setEditable(false);
        txt_codigo_asociado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_codigo_asociado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_codigo_asociado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codigo_asociadoKeyTyped(evt);
            }
        });

        lb_nombre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre1.setText("Numero Asociado");

        txt_nombre_proyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nombre_proyecto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_nombre_proyecto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombre_proyectoKeyTyped(evt);
            }
        });

        lb_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre.setText("Nombre de Proyecto");

        lb_nombre2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre2.setText("Descripcion de Proyecto");

        lb_nombre3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre3.setText("Fecha de Inicio");

        lb_nombre4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre4.setText("Fecha de Finalizacion");

        txt_descripcion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_descripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb_nombre4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_nombre)
                                    .addComponent(lb_nombre1)
                                    .addComponent(lb_nombre3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nombre_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_codigo_asociado, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lb_nombre2)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombre1)
                    .addComponent(txt_codigo_asociado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nombre3)
                    .addComponent(fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nombre4)
                    .addComponent(fecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_nombre2)
                .addGap(7, 7, 7)
                .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Buscar Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lb_nombre5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre5.setText("Nombre Empleado:");

        txt_nombre_empleado.setEditable(false);
        txt_nombre_empleado.setBackground(new java.awt.Color(51, 153, 255));
        txt_nombre_empleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nombre_empleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_nombre_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombre_empleadoKeyTyped(evt);
            }
        });

        btm_buscar_empleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btm_buscar_empleado.setForeground(new java.awt.Color(51, 153, 255));
        btm_buscar_empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados_icono.png"))); // NOI18N
        btm_buscar_empleado.setText("Buscar");
        btm_buscar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_buscar_empleadoActionPerformed(evt);
            }
        });

        txt_documento_empleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_documento_empleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_documento_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_documento_empleadoKeyTyped(evt);
            }
        });

        lb_nombre6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre6.setText("Digete Documento:");

        txt_doc_empe.setEditable(false);
        txt_doc_empe.setBackground(new java.awt.Color(51, 153, 255));
        txt_doc_empe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_doc_empe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_doc_empe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_doc_empeKeyTyped(evt);
            }
        });

        lb_nombre7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre7.setText("Documento :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_nombre6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_documento_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btm_buscar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lb_nombre5)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_doc_empe, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lb_nombre7)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_documento_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nombre6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btm_buscar_empleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_nombre5)
                            .addComponent(lb_nombre7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_doc_empe, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btm_registrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btm_registrar.setForeground(new java.awt.Color(0, 153, 0));
        btm_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proyectos_icono.png"))); // NOI18N
        btm_registrar.setText("Modificar");
        btm_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btm_registrar)
                        .addGap(151, 151, 151))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btm_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigo_asociadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigo_asociadoKeyTyped
        char teclaseleccionada = evt.getKeyChar();
        if (teclaseleccionada == KeyEvent.VK_ENTER || teclaseleccionada == KeyEvent.VK_I) {
            btm_registrar.doClick();
        }

        if (Character.isLetter(teclaseleccionada)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO SE PUEDEN INGRESAR NUMEROS EN EL CAMPO");
        }
    }//GEN-LAST:event_txt_codigo_asociadoKeyTyped

    private void txt_nombre_proyectoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre_proyectoKeyTyped
        char teclaseleccionada = evt.getKeyChar();
        if (teclaseleccionada == KeyEvent.VK_ENTER || teclaseleccionada == KeyEvent.VK_I) {
            btm_registrar.doClick();
        }
    }//GEN-LAST:event_txt_nombre_proyectoKeyTyped

    private void btm_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_registrarActionPerformed
        long numero_empleado = Long.parseLong(txt_codigo_asociado.getText());
        String nombre = txt_nombre_proyecto.getText();
        String descripcion = txt_descripcion.getText();
        Date fecha_i = fecha_inicio.getDate();
        Date fecha_f = fecha_final.getDate();
        long documento_emple = Long.parseLong(txt_doc_empe.getText());
        
        for(Abstracciones.Abs_proyectos p: Metodos.metodos.lista_proyectos){
            if(numero_empleado == p.getNumero_empleados()){
                
                p.setNombre(nombre);
                p.setDescripcion(descripcion);
                p.setFecha_i(fecha_i);
                p.setFecha_f(fecha_f);
                p.setDoc_empleado(documento_emple);                           
                Mantenimiento.btm_actualizar23.doClick();
                Metodos.metodos.guarda_modificacion_proyectos();
                JOptionPane.showMessageDialog(null, "PROYECTO MODIFICADO CON EXITO");
                break;
            }
        }
    }//GEN-LAST:event_btm_registrarActionPerformed

    private void txt_nombre_empleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre_empleadoKeyTyped

    }//GEN-LAST:event_txt_nombre_empleadoKeyTyped

    private void btm_buscar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_buscar_empleadoActionPerformed

        if (!txt_documento_empleado.getText().isEmpty()) {
            boolean existe = false;
            long doc_emple = Long.parseLong(txt_documento_empleado.getText().trim());
            for (Abstracciones.Abs_empleados e : Metodos.metodos.lista_empleados) {
                if (e.getDocumento() == doc_emple) {
                    txt_nombre_empleado.setText(e.getNombre_emple());
                    txt_doc_empe.setText(Long.toString(e.getDocumento()));
                    existe = true;
                    JOptionPane.showMessageDialog(null, "EMPLEADO ENCONTRADO CON EXITO");
                    txt_documento_empleado.setText("");
                    break;
                }
            }
            if (existe == false) {
                JOptionPane.showMessageDialog(null, "EMPLEADO NO EXISTE");
            }
        } else {
            JOptionPane.showMessageDialog(null, "INGRESE DOCUMENTO");
        }
    }//GEN-LAST:event_btm_buscar_empleadoActionPerformed

    private void txt_documento_empleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_documento_empleadoKeyTyped
        char teclaseleccionada = evt.getKeyChar();
        if (teclaseleccionada == KeyEvent.VK_ENTER || teclaseleccionada == KeyEvent.VK_I) {
            btm_buscar_empleado.doClick();
        }
    }//GEN-LAST:event_txt_documento_empleadoKeyTyped

    private void txt_doc_empeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_doc_empeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_doc_empeKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_buscar_empleado;
    private javax.swing.JButton btm_registrar;
    public static com.toedter.calendar.JDateChooser fecha_final;
    public static com.toedter.calendar.JDateChooser fecha_inicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_nombre1;
    private javax.swing.JLabel lb_nombre2;
    private javax.swing.JLabel lb_nombre3;
    private javax.swing.JLabel lb_nombre4;
    private javax.swing.JLabel lb_nombre5;
    private javax.swing.JLabel lb_nombre6;
    private javax.swing.JLabel lb_nombre7;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JPanel panel_titulo;
    public static javax.swing.JTextField txt_codigo_asociado;
    public static javax.swing.JTextField txt_descripcion;
    public static javax.swing.JTextField txt_doc_empe;
    private javax.swing.JTextField txt_documento_empleado;
    public static javax.swing.JTextField txt_nombre_empleado;
    public static javax.swing.JTextField txt_nombre_proyecto;
    // End of variables declaration//GEN-END:variables
}
