/*
 * Este codigo fue creado por @DuvanBotello
 *  <"Sin lógica no hay paraíso">
 */
package GUI;

/**
 *
 * @author DuvanBotello
 * <http://yoaprendo-informatica.blogspot.com.co/ - duvanbotello1008@gmail.com>
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        Metodos.metodos.cargar_datos(this);
        Metodos.metodos.crear_archivos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        lb_bienvenida = new javax.swing.JLabel();
        lb_bienvenida1 = new javax.swing.JLabel();
        lb_bienvenida2 = new javax.swing.JLabel();
        Menu_Pricipal = new javax.swing.JMenuBar();
        Menu_archivos = new javax.swing.JMenu();
        submenu_salir = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Menu_Administracion = new javax.swing.JMenu();
        submenu_empleados = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        submenu_empleados1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        submenu_empleados2 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        submenu_empleados3 = new javax.swing.JMenuItem();
        Menu_Servicios = new javax.swing.JMenu();
        submenu_departamentos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        submenu_proyectos = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        submenu_proyectos2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");

        lb_bienvenida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_bienvenida.setForeground(new java.awt.Color(255, 255, 255));
        lb_bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_bienvenida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lb_bienvenida1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_bienvenida1.setForeground(new java.awt.Color(255, 255, 255));
        lb_bienvenida1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_bienvenida1.setText("2017");
        lb_bienvenida1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lb_bienvenida2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_bienvenida2.setForeground(new java.awt.Color(255, 255, 255));
        lb_bienvenida2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_bienvenida2.setText("PROGRAMACION ORIENTADA A OBJETOS");
        lb_bienvenida2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        escritorio.setLayer(lb_bienvenida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lb_bienvenida1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lb_bienvenida2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_bienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
            .addComponent(lb_bienvenida1, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lb_bienvenida2, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(lb_bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lb_bienvenida1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 348, Short.MAX_VALUE))
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(escritorioLayout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(lb_bienvenida2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(382, Short.MAX_VALUE)))
        );

        Menu_Pricipal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Menu_archivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_parcial.png"))); // NOI18N
        Menu_archivos.setText("Archivos");
        Menu_archivos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        submenu_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        submenu_salir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submenu_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir_icono.png"))); // NOI18N
        submenu_salir.setText("Cerrar Sesion");
        submenu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_salirActionPerformed(evt);
            }
        });
        Menu_archivos.add(submenu_salir);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/parcial_icono.png"))); // NOI18N
        jMenuItem1.setText("Parcial");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Menu_archivos.add(jMenuItem1);

        Menu_Pricipal.add(Menu_archivos);

        Menu_Administracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/admin_icono.png"))); // NOI18N
        Menu_Administracion.setText("Administracion");
        Menu_Administracion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        submenu_empleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        submenu_empleados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submenu_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados_icono.png"))); // NOI18N
        submenu_empleados.setText("Registro De Empleados");
        submenu_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_empleadosActionPerformed(evt);
            }
        });
        Menu_Administracion.add(submenu_empleados);
        Menu_Administracion.add(jSeparator2);

        submenu_empleados1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        submenu_empleados1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submenu_empleados1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes_icono.png"))); // NOI18N
        submenu_empleados1.setText("Reportes");
        submenu_empleados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_empleados1ActionPerformed(evt);
            }
        });
        Menu_Administracion.add(submenu_empleados1);
        Menu_Administracion.add(jSeparator3);

        submenu_empleados2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        submenu_empleados2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submenu_empleados2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar_icono.png"))); // NOI18N
        submenu_empleados2.setText("Mantenimiento");
        submenu_empleados2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_empleados2ActionPerformed(evt);
            }
        });
        Menu_Administracion.add(submenu_empleados2);
        Menu_Administracion.add(jSeparator4);

        submenu_empleados3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        submenu_empleados3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submenu_empleados3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados_icono.png"))); // NOI18N
        submenu_empleados3.setText("Asignar Rol");
        submenu_empleados3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_empleados3ActionPerformed(evt);
            }
        });
        Menu_Administracion.add(submenu_empleados3);

        Menu_Pricipal.add(Menu_Administracion);

        Menu_Servicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/servicios_icono.png"))); // NOI18N
        Menu_Servicios.setText("Servicios");
        Menu_Servicios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        submenu_departamentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        submenu_departamentos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submenu_departamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/departamentos_icono.png"))); // NOI18N
        submenu_departamentos.setText("Registro De Departamentos");
        submenu_departamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_departamentosActionPerformed(evt);
            }
        });
        Menu_Servicios.add(submenu_departamentos);
        Menu_Servicios.add(jSeparator1);

        submenu_proyectos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        submenu_proyectos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submenu_proyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proyectos_icono.png"))); // NOI18N
        submenu_proyectos.setText("Registro De Proyectos");
        submenu_proyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_proyectosActionPerformed(evt);
            }
        });
        Menu_Servicios.add(submenu_proyectos);
        Menu_Servicios.add(jSeparator6);

        submenu_proyectos2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        submenu_proyectos2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submenu_proyectos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes_icono.png"))); // NOI18N
        submenu_proyectos2.setText("Asignar Departamentos a E");
        submenu_proyectos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_proyectos2ActionPerformed(evt);
            }
        });
        Menu_Servicios.add(submenu_proyectos2);

        Menu_Pricipal.add(Menu_Servicios);

        setJMenuBar(Menu_Pricipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submenu_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_empleadosActionPerformed
       Rempleados Registro_Empleados = new Rempleados();
      escritorio.add(Registro_Empleados);
      Registro_Empleados.show();
    }//GEN-LAST:event_submenu_empleadosActionPerformed

    private void submenu_empleados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_empleados1ActionPerformed
       Reportes repor = new Reportes();
       escritorio.add(repor);
       repor.show();
    }//GEN-LAST:event_submenu_empleados1ActionPerformed

    private void submenu_empleados2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_empleados2ActionPerformed
      Mantenimiento mante = new Mantenimiento();
      escritorio.add(mante);
      mante.show();
    }//GEN-LAST:event_submenu_empleados2ActionPerformed

    private void submenu_empleados3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_empleados3ActionPerformed
       R_Administradores admin = new R_Administradores();
       escritorio.add(admin);
       admin.show();
    }//GEN-LAST:event_submenu_empleados3ActionPerformed

    private void submenu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_salirActionPerformed
        Login dd = new Login();
        dd.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_submenu_salirActionPerformed

    private void submenu_departamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_departamentosActionPerformed
       Rdepartamentos depar = new Rdepartamentos();
       escritorio.add(depar);
       depar.show();
    }//GEN-LAST:event_submenu_departamentosActionPerformed

    private void submenu_proyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_proyectosActionPerformed
       Rproyectos proyec = new Rproyectos();
       escritorio.add(proyec);
       proyec.show();
    }//GEN-LAST:event_submenu_proyectosActionPerformed

    private void submenu_proyectos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_proyectos2ActionPerformed
       Asignar_departamentos d = new Asignar_departamentos();
       escritorio.add(d);
       d.show();
    }//GEN-LAST:event_submenu_proyectos2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Parcial p = new Parcial();
        escritorio.add(p);
        p.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_Administracion;
    private javax.swing.JMenuBar Menu_Pricipal;
    private javax.swing.JMenu Menu_Servicios;
    private javax.swing.JMenu Menu_archivos;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    public static javax.swing.JLabel lb_bienvenida;
    public static javax.swing.JLabel lb_bienvenida1;
    public static javax.swing.JLabel lb_bienvenida2;
    private javax.swing.JMenuItem submenu_departamentos;
    private javax.swing.JMenuItem submenu_empleados;
    private javax.swing.JMenuItem submenu_empleados1;
    private javax.swing.JMenuItem submenu_empleados2;
    private javax.swing.JMenuItem submenu_empleados3;
    private javax.swing.JMenuItem submenu_proyectos;
    private javax.swing.JMenuItem submenu_proyectos2;
    private javax.swing.JMenuItem submenu_salir;
    // End of variables declaration//GEN-END:variables
}
