/*
 * Este codigo fue creado por @DuvanBotello
 *  <"Sin lógica no hay paraíso">
 */
package GUI;

import Abstracciones.Abs_departamentos;
import Abstracciones.Abs_empleados;
import Abstracciones.Abs_proyectos;
import static GUI.Mantenimiento.tb1;
import Metodos.Render;
import Metodos.metodos;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DuvanBotello
 * <http://yoaprendo-informatica.blogspot.com.co/ - duvanbotello1008@gmail.com>
 */
public class Rdepartamentos extends javax.swing.JInternalFrame {

    DefaultTableModel modelo_empleado = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    JButton btn1 = new JButton("Asignar");
    private TableRowSorter<TableModel> trs;

    /**
     * Creates new form Rdepartamentos
     */
    public Rdepartamentos() {
        initComponents();
        cargar();
    }

    private void cargar() {
        tb1.setModel(modelo_empleado);
        tb1.setRowHeight(30);
        tb1.setDefaultRenderer(Object.class, new Render());

        btn1.setName("btm_Asignar");

        modelo_empleado.addColumn("Documento");
        modelo_empleado.addColumn("Nombre");
        modelo_empleado.addColumn("Num_Seguridad");
        modelo_empleado.addColumn("Direccion");
        modelo_empleado.addColumn("Sueldo");
        modelo_empleado.addColumn("Genero");
        modelo_empleado.addColumn("Hijos");
        modelo_empleado.addColumn("Fecha_na");
        modelo_empleado.addColumn("Asignar");
        tb1.setModel(modelo_empleado);
        cargar_tabla_empleados();
    }

    private void cargar_tabla_empleados() {
        modelo_empleado.setRowCount(0);
        Object[] file = new Object[tb1.getColumnCount()];
        for (Abs_empleados e : metodos.lista_empleados) {
            file[0] = e.getDocumento();
            file[1] = e.getNombre_emple();
            file[2] = e.getNum_seguridad_s();
            file[3] = e.getDireccion();
            file[4] = "$" + e.getSueldo();
            file[5] = e.getGenero();
            file[6] = e.getNumero_hijos();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            file[7] = formato.format(e.getFecha_nacimiento());
            file[8] = btn1;
            modelo_empleado.addRow(file);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_titulo = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_nombre_departamento = new javax.swing.JTextField();
        lb_nombre = new javax.swing.JLabel();
        lb_nombre1 = new javax.swing.JLabel();
        txt_codigo_departamento = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lb_nombre4 = new javax.swing.JLabel();
        txt_documento_asigndo = new javax.swing.JTextField();
        txt_nombre_emple_Asig = new javax.swing.JTextField();
        lb_nombre5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        lb_nombre2 = new javax.swing.JLabel();
        combo_busqueda = new javax.swing.JComboBox<>();
        txt_buscar = new javax.swing.JTextField();
        lb_nombre3 = new javax.swing.JLabel();
        fecha_departamento = new com.toedter.calendar.JDateChooser();
        btm_registrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registro de Departamentos");

        panel_titulo.setBackground(new java.awt.Color(51, 51, 51));
        panel_titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_titulo.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo.setText("Registro de Departamentos");

        javax.swing.GroupLayout panel_tituloLayout = new javax.swing.GroupLayout(panel_titulo);
        panel_titulo.setLayout(panel_tituloLayout);
        panel_tituloLayout.setHorizontalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tituloLayout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(lb_titulo)
                .addGap(186, 186, 186))
        );
        panel_tituloLayout.setVerticalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloLayout.createSequentialGroup()
                .addComponent(lb_titulo)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos de Departamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txt_nombre_departamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nombre_departamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_nombre_departamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombre_departamentoKeyTyped(evt);
            }
        });

        lb_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre.setText("Nombre de Departamento:");

        lb_nombre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre1.setText("Codigo de departamento:");

        txt_codigo_departamento.setEditable(false);
        txt_codigo_departamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_codigo_departamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_codigo_departamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codigo_departamentoKeyTyped(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos de Empleado Asignado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lb_nombre4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre4.setText("Documento:");

        txt_documento_asigndo.setEditable(false);
        txt_documento_asigndo.setBackground(new java.awt.Color(255, 153, 153));
        txt_documento_asigndo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_documento_asigndo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_documento_asigndo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_documento_asigndoKeyTyped(evt);
            }
        });

        txt_nombre_emple_Asig.setEditable(false);
        txt_nombre_emple_Asig.setBackground(new java.awt.Color(255, 153, 153));
        txt_nombre_emple_Asig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nombre_emple_Asig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_nombre_emple_Asig.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombre_emple_AsigKeyTyped(evt);
            }
        });

        lb_nombre5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre5.setText("Nombre:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_nombre4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_documento_asigndo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_nombre5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombre_emple_Asig, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombre4)
                    .addComponent(txt_documento_asigndo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombre5)
                    .addComponent(txt_nombre_emple_Asig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Asignar Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        lb_nombre2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre2.setText("Buscar por:");

        combo_busqueda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_busqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "DOCUMENTO", "NOMBRE" }));

        txt_buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_nombre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nombre2)
                    .addComponent(combo_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lb_nombre3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre3.setText("Fecha de Iniciacion : ");

        btm_registrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btm_registrar.setForeground(new java.awt.Color(0, 153, 0));
        btm_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/departamentos_icono.png"))); // NOI18N
        btm_registrar.setText("Registar Departamento");
        btm_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_registrarActionPerformed(evt);
            }
        });

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_nombre1)
                            .addComponent(lb_nombre)
                            .addComponent(lb_nombre3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nombre_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_codigo_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(fecha_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(btm_registrar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombre)
                    .addComponent(txt_nombre_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_nombre1)
                            .addComponent(txt_codigo_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_nombre3)
                            .addComponent(fecha_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombre_departamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre_departamentoKeyTyped
        char teclaseleccionada = evt.getKeyChar();
        if (teclaseleccionada == KeyEvent.VK_ENTER || teclaseleccionada == KeyEvent.VK_I) {
            btm_registrar.doClick();
        }
    }//GEN-LAST:event_txt_nombre_departamentoKeyTyped

    private void txt_codigo_departamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigo_departamentoKeyTyped
        char teclaseleccionada = evt.getKeyChar();
        if (teclaseleccionada == KeyEvent.VK_ENTER || teclaseleccionada == KeyEvent.VK_I) {
            btm_registrar.doClick();
        }

        if (Character.isLetter(teclaseleccionada)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO SE PUEDEN INGRESAR NUMEROS EN EL CAMPO");
        }
    }//GEN-LAST:event_txt_codigo_departamentoKeyTyped

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        int seleccion = tb1.rowAtPoint(evt.getPoint());
        String documento = String.valueOf(tb1.getValueAt(seleccion, 0));
        String nombre = String.valueOf(tb1.getValueAt(seleccion, 1));

        //CON ESTO AGARRO LA POSICION X Y LA Y PARA SABER LA UBICACION
        int column = tb1.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tb1.getRowHeight();

        if (row < tb1.getRowCount() && row >= 0 && column < tb1.getColumnCount() && column >= 0) {
            Object value = tb1.getValueAt(row, column);
            //SI LA POCICION DONDE SE DIO CLIK ES UN BOTON SE PUEDE EJECUTAR EL CODIGO
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("btm_Asignar")) {
                    txt_nombre_emple_Asig.setText(nombre);
                    txt_documento_asigndo.setText(documento);

                }
            }

        }
    }//GEN-LAST:event_tb1MouseClicked

    private void txt_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyTyped

        switch (combo_busqueda.getSelectedIndex()) {
            case 1:

                txt_buscar.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt_buscar.getText(), 0));
                    }

                });
                trs = new TableRowSorter<>(tb1.getModel());
                tb1.setRowSorter(trs);
                break;
            case 2:
                txt_buscar.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt_buscar.getText(), 1));
                    }

                });
                trs = new TableRowSorter<>(tb1.getModel());
                tb1.setRowSorter(trs);

                break;
            default:
                JOptionPane.showMessageDialog(null, "Por favor seleccione un tipo de busqueda");

                break;
        }
    }//GEN-LAST:event_txt_buscarKeyTyped

    private void btm_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_registrarActionPerformed
        boolean validar_datos = validar_datos();
        if (validar_datos == true) {
            if (llave_codigo() == false) {
                String nombre_departamento = txt_nombre_departamento.getText();
                long codigo_departamento = Long.parseLong(txt_codigo_departamento.getText().trim());
                long documento = Long.parseLong(txt_documento_asigndo.getText());
                Abs_empleados f = null;
                for (Abs_empleados d : metodos.lista_empleados) {
                    if (documento == d.getDocumento()) {
                        f = d;
                        break;
                    }
                }
                Date fecha_dige = fecha_departamento.getDate();
                LinkedList<Abstracciones.Abs_proyectos> listaproyecto = new LinkedList<>();
                
                metodos.agregar_departamento(new Abs_departamentos(nombre_departamento, codigo_departamento, f, fecha_dige, listaproyecto));
                metodos.InsertaDepartamento(new Abs_departamentos(nombre_departamento, codigo_departamento, f, fecha_dige, listaproyecto), txt_nombre_departamento.getText());
                limpiar_campos();
            } else {
                JOptionPane.showMessageDialog(null, "El nombre: "+txt_nombre_departamento.getText()+" Ya existe");
            }

        }

    }//GEN-LAST:event_btm_registrarActionPerformed
    private void limpiar_campos(){
        txt_codigo_departamento.setText("");
        txt_documento_asigndo.setText("");
        txt_nombre_departamento.setText("");
        txt_nombre_emple_Asig.setText("");
        fecha_departamento.setDate(null);
    }
    private boolean llave_codigo() {
        boolean existe = false;
        for (Abs_departamentos f : metodos.lista_departamentos) {
            if (txt_nombre_departamento.getText().trim().equals(f.getNombre())) {
                existe = true;
                break;
            }
        }
        return existe;
    }

    private boolean validar_datos() {
        boolean existe = false;
        if (!txt_nombre_departamento.getText().isEmpty()) {
            if (!txt_codigo_departamento.getText().isEmpty()) {
                if (fecha_departamento.getDate() != null) {

                    if (!txt_documento_asigndo.getText().isEmpty()) {

                        existe = true;

                    } else {
                        JOptionPane.showMessageDialog(null, "Asigne un empleado al departamento");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Ingrese Fecha");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese codigo de departamento");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese Nombre de departamento");
        }

        return existe;
    }
    private void txt_documento_asigndoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_documento_asigndoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_documento_asigndoKeyTyped

    private void txt_nombre_emple_AsigKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre_emple_AsigKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_emple_AsigKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      long codigo = metodos.lista_departamentos.size() + 1000;
      txt_codigo_departamento.setText(Long.toString(codigo));
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_registrar;
    private javax.swing.JComboBox<String> combo_busqueda;
    private com.toedter.calendar.JDateChooser fecha_departamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_nombre1;
    private javax.swing.JLabel lb_nombre2;
    private javax.swing.JLabel lb_nombre3;
    private javax.swing.JLabel lb_nombre4;
    private javax.swing.JLabel lb_nombre5;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JPanel panel_titulo;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_codigo_departamento;
    private javax.swing.JTextField txt_documento_asigndo;
    private javax.swing.JTextField txt_nombre_departamento;
    private javax.swing.JTextField txt_nombre_emple_Asig;
    // End of variables declaration//GEN-END:variables
}
