/*
 * Este codigo fue creado por @DuvanBotello
 *  <"Sin lógica no hay paraíso">
 */
package GUI;

import Abstracciones.Abs_departamentos;
import Abstracciones.Abs_empleados;
import Abstracciones.Abs_proyectos;
import Metodos.Render;
import Metodos.metodos;
import java.awt.Desktop;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DuvanBotello
 * <http://yoaprendo-informatica.blogspot.com.co/ - duvanbotello1008@gmail.com>
 */
public class Reportes extends javax.swing.JInternalFrame {

    DefaultTableModel modelo_departamentos = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    DefaultTableModel modelo_empleado = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    JButton btn1 = new JButton("Generar Reporte");
    private TableRowSorter<TableModel> trs;

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
        cargar();
        cargar_modelo_emple();
    }

    private void cargar_modelo_emple() {
        tb2.setModel(modelo_empleado);
        tb2.setRowHeight(30);
        tb2.setDefaultRenderer(Object.class, new Render());

        btn1.setName("btm_reporte");

        modelo_empleado.addColumn("Documento");
        modelo_empleado.addColumn("Nombre");
        modelo_empleado.addColumn("Generar Reporte De Proyectos");
        tb2.setModel(modelo_empleado);
        cargar_tabla_empleados();

    }

    private void cargar_tabla_empleados() {
        modelo_empleado.setRowCount(0);
        Object[] file = new Object[tb2.getColumnCount()];
        for (Abs_empleados e : metodos.lista_empleados) {
            file[0] = e.getDocumento();
            file[1] = e.getNombre_emple();
            file[2] = btn1;
            modelo_empleado.addRow(file);
        }
    }

    private void cargar() {
        tb1.setModel(modelo_departamentos);
        tb1.setRowHeight(30);
        tb1.setDefaultRenderer(Object.class, new Render());

        btn1.setName("btm_reporte");

        modelo_departamentos.addColumn("Nombre Departamento");
        modelo_departamentos.addColumn("Codigo");
        modelo_departamentos.addColumn("Fecha de Inicio");
        modelo_departamentos.addColumn("Generar Reporte");

        tb1.setModel(modelo_departamentos);
        cargar_tabla_despartamentos();

    }

    private void cargar_tabla_despartamentos() {
        modelo_departamentos.setRowCount(0);
        Object[] file = new Object[tb1.getColumnCount()];
        for (Abs_departamentos d : metodos.lista_departamentos) {

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            file[0] = d.getNombre();
            file[1] = d.getCodigo();
            file[2] = formato.format(d.getFecha_dirige());
            file[3] = btn1;
            modelo_departamentos.addRow(file);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_titulo = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        tabulacion_panel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        combo_busqueda = new javax.swing.JComboBox<>();
        lb_nombre = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        combo_busqueda1 = new javax.swing.JComboBox<>();
        lb_nombre1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lb_nombre3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btm_reporte_fecha = new javax.swing.JButton();
        fecha_inicial = new com.toedter.calendar.JDateChooser();
        lb_nombre4 = new javax.swing.JLabel();
        fecha_final = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        combo_genero = new javax.swing.JComboBox<>();
        lb_nombre2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Reportes");

        panel_titulo.setBackground(new java.awt.Color(51, 51, 51));
        panel_titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_titulo.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo.setText("Reportes");

        javax.swing.GroupLayout panel_tituloLayout = new javax.swing.GroupLayout(panel_titulo);
        panel_titulo.setLayout(panel_tituloLayout);
        panel_tituloLayout.setHorizontalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(lb_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_tituloLayout.setVerticalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloLayout.createSequentialGroup()
                .addComponent(lb_titulo)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        tabulacion_panel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/departamentos_icono.png"))); // NOI18N
        jButton1.setText("Listado de Departamentos");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados_icono.png"))); // NOI18N
        jButton2.setText("Listado de Empleados");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proyectos_icono.png"))); // NOI18N
        jButton3.setText("Listado de proyectos");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados_icono.png"))); // NOI18N
        jButton4.setText("Empleados con mas de 2 hijos.");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados_icono.png"))); // NOI18N
        jButton5.setText("Empleados con suldo mayor a $1.000.000");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        tabulacion_panel.addTab("Generar Listados", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Buscar Departamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        combo_busqueda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_busqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "NOMBRE", "CODIGO" }));

        lb_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre.setText("Buscar por:");

        txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lb_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nombre)
                    .addComponent(combo_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tabulacion_panel.addTab("Proyectos Segun Departamentos", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Buscar Empleados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb2);

        combo_busqueda1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_busqueda1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "DOCUMENTO", "NOMBRE" }));

        lb_nombre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre1.setText("Buscar por:");

        txt1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lb_nombre1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_busqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nombre1)
                    .addComponent(combo_busqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabulacion_panel.addTab("Proyecto segun Empelado", jPanel3);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Proyecto Segun Fechas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lb_nombre3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre3.setText("Fecha Inicial:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Listado de proyectos según fecha de inicio y terminación");

        btm_reporte_fecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btm_reporte_fecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proyectos_icono.png"))); // NOI18N
        btm_reporte_fecha.setText("GENERAR REPORTE");
        btm_reporte_fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btm_reporte_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_reporte_fechaActionPerformed(evt);
            }
        });

        lb_nombre4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre4.setText("Fecha Final:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(btm_reporte_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(lb_nombre3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(lb_nombre4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nombre3)
                    .addComponent(fecha_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nombre4)
                    .addComponent(fecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btm_reporte_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabulacion_panel.addTab("Proyectos Segun fechas", jPanel4);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Empleados Segun genero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        combo_genero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "MASCULINO", "FEMENINO" }));

        lb_nombre2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nombre2.setText("Genero:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Listado de empleados según género y el sueldo es menor o igual a  2.000.000 o tengan más de 3 hijos.");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados_icono.png"))); // NOI18N
        jButton6.setText("GENERAR REPORTE");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(lb_nombre2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nombre2))
                .addGap(58, 58, 58)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tabulacion_panel.addTab("Empleados Segun genero", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabulacion_panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabulacion_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        File reporte_empleados = new File("src/Reportes/Reporte_departamentos.xls");
        try {
            reporte_empleados.delete();
            reporte_empleados.createNewFile();
            BufferedWriter Fescribe = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(reporte_empleados, true), "utf-8"));
            Fescribe.write("------------------------------------------REPORTE DE DEPARTAMENTOS-----------------------------------------------" + "\r\n");
            Fescribe.write("NOMBRE DEPARTAMENTO" + "\t" + "CODIGO" + "\t" + "DOC EMPLEADO ENCARGADI" + "\t" + "FECHA QUE EMPEZO" + "\t" + "LISTA DE PROYECTOS" + "\r\n");

            for (Abstracciones.Abs_departamentos e : Metodos.metodos.lista_departamentos) {
                String fecha1 = new SimpleDateFormat("dd/MM/yyyy").format(e.getFecha_dirige());
                Fescribe.write(e.getNombre() + "\t" + e.getCodigo() + "\t" + e.getEmple().getDocumento() + "\t" + fecha1 + "\t" + e.getListaproyecto() + "\r\n");
            }
            Fescribe.close();

            int option = JOptionPane.showConfirmDialog(null, "¿Desea Abrir el archivo?", "Abrir el archivo", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                Desktop.getDesktop().open(reporte_empleados);
            }

        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        File reporte_empleados = new File("src/Reportes/Reporte_Empleados.xls");
        try {
            reporte_empleados.delete();
            reporte_empleados.createNewFile();
            BufferedWriter Fescribe = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(reporte_empleados, true), "utf-8"));
            Fescribe.write("------------------------------------------REPORTE DE EMPLEADOS-----------------------------------------------" + "\r\n");
            Fescribe.write("DOCUMENTO" + "\t" + "NOMBRE EMPLEADO" + "\t" + "NUM SEGURIDAD" + "\t" + "DIRECCION" + "\t" + "SUELDO" + "\t" + "GENERO" + "\t" + "HIJOS" + "\t"
                    + "FECHA DE NACI" + "\t" + "DEPARTAMENTO" + "\r\n");

            for (Abstracciones.Abs_empleados e : Metodos.metodos.lista_empleados) {

                String fecha1 = new SimpleDateFormat("dd/MM/yyyy").format(e.getFecha_nacimiento());
                Fescribe.write(e.getDocumento() + "\t" + e.getNombre_emple() + "\t" + e.getNum_seguridad_s() + "\t" + e.getDireccion()
                        + "\t" + e.getSueldo() + "\t" + e.getGenero() + "\t" + e.getNumero_hijos() + "\t" + fecha1 + "\t" + e.getDepartamento_asignado() + "\r\n");

            }
            Fescribe.close();

            int option = JOptionPane.showConfirmDialog(null, "¿Desea Abrir el archivo?", "Abrir el archivo", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                Desktop.getDesktop().open(reporte_empleados);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        File reporte_proyectos = new File("src/Reportes/Reporte_proyectos.xls");
        try {
            reporte_proyectos.delete();
            reporte_proyectos.createNewFile();
            BufferedWriter Fescribe = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(reporte_proyectos, true), "utf-8"));
            Fescribe.write("------------------------------------------REPORTE DE PROYECTOS EN GENERAL-----------------------------------------------" + "\r\n");
            Fescribe.write("ID DE PROYECTO" + "\t" + "NOMBRE PROYECTO" + "\t" + "DESCIPCION" + "\t" + "FECHA INICIAL" + "\t" + "FECHA FINAL" + "\t" + "DOCUMENTO EMPELADO" + "\r\n");
            for (Abstracciones.Abs_proyectos p : Metodos.metodos.lista_proyectos) {

                String fechai = new SimpleDateFormat("dd/MM/yyyy").format(p.getFecha_i());
                String fechaf = new SimpleDateFormat("dd/MM/yyyy").format(p.getFecha_f());
                Fescribe.write(p.getNumero_empleados() + "\t" + p.getNombre() + "\t" + p.getDescripcion() + "\t" + fechai + "\t" + fechaf
                        + "\t" + p.getDoc_empleado() + "\r\n");

            }
            Fescribe.close();

            int option = JOptionPane.showConfirmDialog(null, "¿Desea Abrir el archivo?", "Abrir el archivo", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                Desktop.getDesktop().open(reporte_proyectos);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        File reporte_empleado_mayor_2hijos = new File("src/Reportes/Reporte_Empleado_conMas_2hijos.xls");
        try {
            reporte_empleado_mayor_2hijos.delete();
            reporte_empleado_mayor_2hijos.createNewFile();
            BufferedWriter Fescribe = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(reporte_empleado_mayor_2hijos, true), "utf-8"));
            Fescribe.write("------------------------------------------REPORTE DE EMPLEADO CON MAS DE DOS HIJOS-----------------------------------------------" + "\r\n");
            Fescribe.write("DOCUMENTO" + "\t" + "NOMBRE EMPLEADO" + "\t" + "NUM SEGURIDAD" + "\t" + "DIRECCION" + "\t" + "SUELDO" + "\t" + "GENERO" + "\t" + "HIJOS" + "\t"
                    + "FECHA DE NACI" + "\t" + "DEPARTAMENTO" + "\r\n");
            for (Abstracciones.Abs_empleados e : Metodos.metodos.lista_empleados) {

                if (e.getNumero_hijos() > 2) {
                    String fecha1 = new SimpleDateFormat("dd/MM/yyyy").format(e.getFecha_nacimiento());
                    Fescribe.write(e.getDocumento() + "\t" + e.getNombre_emple() + "\t" + e.getNum_seguridad_s() + "\t" + e.getDireccion()
                            + "\t" + e.getSueldo() + "\t" + e.getGenero() + "\t" + e.getNumero_hijos() + "\t" + fecha1 + "\t" + e.getDepartamento_asignado() + "\r\n");
                }

            }
            Fescribe.close();

            int option = JOptionPane.showConfirmDialog(null, "¿Desea Abrir el archivo?", "Abrir el archivo", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                Desktop.getDesktop().open(reporte_empleado_mayor_2hijos);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        File reporte_empleado_sueldo = new File("src/Reportes/Reporte_Empleado_consueldo.xls");
        try {
            reporte_empleado_sueldo.delete();
            reporte_empleado_sueldo.createNewFile();
            BufferedWriter Fescribe = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(reporte_empleado_sueldo, true), "utf-8"));
            Fescribe.write("------------------------------------------REPORTE DE EMPLEADO CON SUEDLO MAYOR A 1.000.000-----------------------------------------------" + "\r\n");
            Fescribe.write("DOCUMENTO" + "\t" + "NOMBRE EMPLEADO" + "\t" + "NUM SEGURIDAD" + "\t" + "DIRECCION" + "\t" + "SUELDO" + "\t" + "GENERO" + "\t" + "HIJOS" + "\t"
                    + "FECHA DE NACI" + "\t" + "DEPARTAMENTO" + "\r\n");
            for (Abstracciones.Abs_empleados e : Metodos.metodos.lista_empleados) {

                if (e.getSueldo() > 1000000) {
                    String fecha1 = new SimpleDateFormat("dd/MM/yyyy").format(e.getFecha_nacimiento());
                    Fescribe.write(e.getDocumento() + "\t" + e.getNombre_emple() + "\t" + e.getNum_seguridad_s() + "\t" + e.getDireccion()
                            + "\t" + e.getSueldo() + "\t" + e.getGenero() + "\t" + e.getNumero_hijos() + "\t" + fecha1 + "\t" + e.getDepartamento_asignado() + "\r\n");
                }

            }
            Fescribe.close();

            int option = JOptionPane.showConfirmDialog(null, "¿Desea Abrir el archivo?", "Abrir el archivo", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                Desktop.getDesktop().open(reporte_empleado_sueldo);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        int seleccion = tb1.rowAtPoint(evt.getPoint());
        String codigo1 = String.valueOf(tb1.getValueAt(seleccion, 1));
        long codigo = Long.parseLong(codigo1);

        //CON ESTO AGARRO LA POSICION X Y LA Y PARA SABER LA UBICACION
        int column = tb1.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tb1.getRowHeight();

        if (row < tb1.getRowCount() && row >= 0 && column < tb1.getColumnCount() && column >= 0) {
            Object value = tb1.getValueAt(row, column);
            //SI LA POCICION DONDE SE DIO CLIK ES UN BOTON SE PUEDE EJECUTAR EL CODIGO
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("btm_reporte")) {
                    File reporte_departamentos = new File("src/Reportes/Reporte_proyectos_departamentos.xls");
                    try {
                        reporte_departamentos.delete();
                        reporte_departamentos.createNewFile();
                        BufferedWriter Fescribe = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(reporte_departamentos, true), "utf-8"));
                        for (Abs_departamentos d : metodos.lista_departamentos) {
                            if (codigo == d.getCodigo()) {
                                for (Abs_proyectos p : d.getListaproyecto()) {
                                    String fechai = new SimpleDateFormat("dd/MM/yyyy").format(p.getFecha_i());
                                    String fechaf = new SimpleDateFormat("dd/MM/yyyy").format(p.getFecha_f());
                                    Fescribe.write(p.getNumero_empleados() + "\t" + p.getNombre() + "\t" + p.getDescripcion() + "\t" + fechai + "\t" + fechaf
                                            + "\t" + p.getDoc_empleado() + "\r\n");
                                }
                            }
                        }
                        Fescribe.close();

                        int option = JOptionPane.showConfirmDialog(null, "¿Desea Abrir el archivo?", "Abrir el archivo", JOptionPane.YES_NO_OPTION);
                        if (option == JOptionPane.YES_OPTION) {
                            Desktop.getDesktop().open(reporte_departamentos);
                        }

                    } catch (Exception e) {
                    }

                }

            }

        }
    }//GEN-LAST:event_tb1MouseClicked

    private void txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyTyped
        switch (combo_busqueda.getSelectedIndex()) {
            case 1:

                txt.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt.getText(), 0));
                    }

                });
                trs = new TableRowSorter<>(tb1.getModel());
                tb1.setRowSorter(trs);
                break;
            case 2:
                txt.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt.getText(), 1));
                    }

                });
                trs = new TableRowSorter<>(tb1.getModel());
                tb1.setRowSorter(trs);

                break;
            default:
                JOptionPane.showMessageDialog(null, "Por favor seleccione un tipo de busqueda");

                break;
        }
    }//GEN-LAST:event_txtKeyTyped

    private void tb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb2MouseClicked
        int seleccion = tb2.rowAtPoint(evt.getPoint());
        String codigo1 = String.valueOf(tb2.getValueAt(seleccion, 0));
        long documento = Long.parseLong(codigo1);

        //CON ESTO AGARRO LA POSICION X Y LA Y PARA SABER LA UBICACION
        int column = tb2.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tb2.getRowHeight();

        if (row < tb2.getRowCount() && row >= 0 && column < tb2.getColumnCount() && column >= 0) {
            Object value = tb2.getValueAt(row, column);
            //SI LA POCICION DONDE SE DIO CLIK ES UN BOTON SE PUEDE EJECUTAR EL CODIGO
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("btm_reporte")) {
                    File reporte_empleado_proyec = new File("src/Reportes/Reporte_proyectos_empleado.xls");
                    try {
                        reporte_empleado_proyec.delete();
                        reporte_empleado_proyec.createNewFile();
                        BufferedWriter Fescribe = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(reporte_empleado_proyec, true), "utf-8"));
                        for (Abs_proyectos p : metodos.lista_proyectos) {
                            if (documento == p.getDoc_empleado()) {
                                String fechai = new SimpleDateFormat("dd/MM/yyyy").format(p.getFecha_i());
                                String fechaf = new SimpleDateFormat("dd/MM/yyyy").format(p.getFecha_f());
                                Fescribe.write(p.getNumero_empleados() + "\t" + p.getNombre() + "\t" + p.getDescripcion() + "\t" + fechai + "\t" + fechaf
                                        + "\t" + p.getDoc_empleado() + "\r\n");
                            }
                        }
                        Fescribe.close();
                        int option = JOptionPane.showConfirmDialog(null, "¿Desea Abrir el archivo?", "Abrir el archivo", JOptionPane.YES_NO_OPTION);
                        if (option == JOptionPane.YES_OPTION) {
                            Desktop.getDesktop().open(reporte_empleado_proyec);
                        }

                    } catch (Exception e) {
                    }

                }

            }

        }
    }//GEN-LAST:event_tb2MouseClicked

    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
        switch (combo_busqueda1.getSelectedIndex()) {
            case 1:

                txt1.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt1.getText(), 0));
                    }

                });
                trs = new TableRowSorter<>(tb2.getModel());
                tb2.setRowSorter(trs);
                break;
            case 2:
                txt1.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt1.getText(), 1));
                    }

                });
                trs = new TableRowSorter<>(tb2.getModel());
                tb2.setRowSorter(trs);

                break;
            default:
                JOptionPane.showMessageDialog(null, "Por favor seleccione un tipo de busqueda");

                break;
        }
    }//GEN-LAST:event_txt1KeyTyped
    private void reporte_segun_genero(int genero) {
        File reporte_empleado_sueldo = new File("src/Reportes/Reporte_Empleado_segungenero.xls");
        try {
            reporte_empleado_sueldo.delete();
            reporte_empleado_sueldo.createNewFile();
            BufferedWriter Fescribe = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(reporte_empleado_sueldo, true), "utf-8"));
            Fescribe.write("-----------------------------REPORTE DE EMPLEADO SEGUN GENERO Y CON MAS DE 3 HIJOS Y CON SUELDO MENOR A $2.000.000----------------------------------------" + "\r\n");
            Fescribe.write("DOCUMENTO" + "\t" + "NOMBRE EMPLEADO" + "\t" + "NUM SEGURIDAD" + "\t" + "DIRECCION" + "\t" + "SUELDO" + "\t" + "GENERO" + "\t" + "HIJOS" + "\t"
                    + "FECHA DE NACI" + "\t" + "DEPARTAMENTO" + "\r\n");
            for (Abstracciones.Abs_empleados e : Metodos.metodos.lista_empleados) {

                if (e.getSueldo() <= 2000000 && e.getGenero() == genero && e.getNumero_hijos() > 3) {
                    String fecha1 = new SimpleDateFormat("dd/MM/yyyy").format(e.getFecha_nacimiento());
                    Fescribe.write(e.getDocumento() + "\t" + e.getNombre_emple() + "\t" + e.getNum_seguridad_s() + "\t" + e.getDireccion()
                            + "\t" + e.getSueldo() + "\t" + e.getGenero() + "\t" + e.getNumero_hijos() + "\t" + fecha1 + "\t" + e.getDepartamento_asignado() + "\r\n");
                }

            }
            Fescribe.close();

            int option = JOptionPane.showConfirmDialog(null, "¿Desea Abrir el archivo?", "Abrir el archivo", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                Desktop.getDesktop().open(reporte_empleado_sueldo);
            }

        } catch (Exception e) {
        }
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (combo_genero.getSelectedIndex() != 0) {
            switch (combo_genero.getSelectedIndex()) {
                case 0:

                    break;
                case 1:
                    reporte_segun_genero(combo_genero.getSelectedIndex());
                    combo_genero.setSelectedIndex(0);
                    break;
                case 2:
                    reporte_segun_genero(combo_genero.getSelectedIndex());
                    combo_genero.setSelectedIndex(0);
                    break;
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un Genero");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btm_reporte_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_reporte_fechaActionPerformed
        if (fecha_inicial.getDate() != null) {
            if (fecha_final.getDate() != null) {
                SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
                File reporte_proyectos = new File("src/Reportes/Reporte_proyectos_fechas.xls");
                String fecha_i = new SimpleDateFormat("dd/MM/yyyy").format(fecha_inicial.getDate());
                String fecha_f = new SimpleDateFormat("dd/MM/yyyy").format(fecha_final.getDate());

                try {
                    reporte_proyectos.delete();
                    reporte_proyectos.createNewFile();
                    BufferedWriter Fescribe = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(reporte_proyectos, true), "utf-8"));
                    Fescribe.write("------------------------------------------REPORTE DE PROYECTOS RANGO DE FECHAS-----------------------------------------------" + "\r\n");
                    Fescribe.write("ID DE PROYECTO" + "\t" + "NOMBRE PROYECTO" + "\t" + "DESCIPCION" + "\t" + "FECHA INICIAL" + "\t" + "FECHA FINAL" + "\t" + "DOCUMENTO EMPELADO" + "\r\n");
                    for (Abs_proyectos p : metodos.lista_proyectos) {

                        try {
                            Date fecha_ini = fecha.parse(fecha_i);
                            Date fecha_fin = fecha.parse(fecha_f);

                            if (p.getFecha_i().compareTo(fecha_ini) >= 0 && p.getFecha_f().compareTo(fecha_fin) <= 0) {

                                String fechai = new SimpleDateFormat("dd/MM/yyyy").format(p.getFecha_i());
                                String fechaf = new SimpleDateFormat("dd/MM/yyyy").format(p.getFecha_f());
                                Fescribe.write(p.getNumero_empleados() + "\t" + p.getNombre() + "\t" + p.getDescripcion() + "\t" + fechai + "\t" + fechaf
                                        + "\t" + p.getDoc_empleado() + "\r\n");

                            }

                        } catch (Exception e) {
                        }

                    }

                    Fescribe.close();

                    int option = JOptionPane.showConfirmDialog(null, "¿Desea Abrir el archivo?", "Abrir el archivo", JOptionPane.YES_NO_OPTION);
                    if (option == JOptionPane.YES_OPTION) {
                        Desktop.getDesktop().open(reporte_proyectos);
                    }
                } catch (Exception e) {
                }

            } else {
                JOptionPane.showMessageDialog(null, "Por favor Ingrese Fecha Final");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor Ingrese Fecha Inicial");
        }
    }//GEN-LAST:event_btm_reporte_fechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_reporte_fecha;
    private javax.swing.JComboBox<String> combo_busqueda;
    private javax.swing.JComboBox<String> combo_busqueda1;
    private javax.swing.JComboBox<String> combo_genero;
    private com.toedter.calendar.JDateChooser fecha_final;
    private com.toedter.calendar.JDateChooser fecha_inicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_nombre1;
    private javax.swing.JLabel lb_nombre2;
    private javax.swing.JLabel lb_nombre3;
    private javax.swing.JLabel lb_nombre4;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JPanel panel_titulo;
    private javax.swing.JTabbedPane tabulacion_panel;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
